# Only for dev
# For deployed version a cloud provider
# for postgres dbs will be used

services:
    health_observer:
        build:
            dockerfile: ./Dockerfile
        container_name: health_observer
        ports:
            - 8000:8000
        depends_on:
            - postgresql
        environment:
            - ENV=prod
            - CONNECTION_STR=postgresql://postgres@postgresql/una_db

    postgresql:
        image: postgres:latest
        container_name: postgresql
        ports:
            - 5432:5432
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
            - POSTGRES_USER=postgres
            - POSTGRES_DB=una_db
