name: deploy

on:
    push:
        branches: ["master"]

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Check out the repo
              uses: actions/checkout@v4

            - name: Log in to Docker Hub
              uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/health_observer:latest

            - name: Deploy Docker container
              run: |
                  docker run -d -p 8000:8000 --name health_observer \
                    -e ENV=${{ secrets.ENV }} \
                    -e CONNECTION_STR=${{ secrets.CONNECTION_STR }} \
                    ${{ secrets.DOCKER_USERNAME }}/health_observer:latest
